include: package:surf_lint_rules/analysis_options.yaml

linter:
  rules:
    comment_references: false
    unnecessary_lambdas: false

analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart