name: notes_firebase_ddd_course
description: Flutter Firebase & DDD Course.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.1.18
  dartz: ^0.10.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_flushbar: ^0.0.2
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_sign_in: ^5.3.3
  injectable: ^1.5.3
  surf_lint_rules: ^1.5.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
