name: notes_firebase_ddd_course
description: Flutter Firebase & DDD Course.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  surf_lint_rules: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
